theme = "rose_pine"

[keys.insert]
j = { k = "normal_mode" }

[editor]
line-number = "relative"
scrolloff = 100
auto-format = true
auto-info = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"
